<a href="https://colab.research.google.com/github/akhildhingra/hello_world/blob/master/python_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/jakevdp/PythonDataScienceHandbook

Launch a live notebook server with these notebooks using binder: https://mybinder.org/

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


**Note** When using file path, instead of 'data/file' use 'drive/My Drive/data/file'

In [1]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [0]:
len?


In [0]:
L=[1,2,3]
L.insert?

In [0]:
def square(a):
    """return square of a number"""
    return a ** 2

In [0]:
square?


In [0]:
len??

In [0]:
square??


In [0]:
#L._<tab>

In [0]:
#from intertools import co<tab>

In [0]:
#import <tab>

In [0]:
#dont work *warning?

In [0]:
str.*find*?

In [0]:
print(In)

['', 'help(len)', "get_ipython().run_line_magic('pinfo', 'len')", "L=[1,2,3]\nget_ipython().run_line_magic('pinfo', 'L.insert')", 'def square(a):\n    """return square of a number"""\n    return a ** 2', "get_ipython().run_line_magic('pinfo', 'square')", "get_ipython().run_line_magic('pinfo2', 'len')", "get_ipython().run_line_magic('pinfo2', 'square')", '#L._', '#from intertools import co<tab>', '#import <tab>', "get_ipython().run_line_magic('psearch', '*warning')", "get_ipython().run_line_magic('psearch', '*warning')", "get_ipython().run_line_magic('psearch', 'str.*find*')", "get_ipython().run_line_magic('psearch', '*warning')", 'print(In)']


In [0]:
!pwd

/nfs


In [0]:
!ls

 adhingra_notebook.ipynb   conda_envs	    link-to-onboarding-notebooks
 adhingra_Untitled.ipynb   employees.text   notebooks
 airflow		   home		   'python tutorial.ipynb'


In [0]:
!echo "printing from shell"

printing from shell


In [0]:
%%file test_file.py
def add_ten(N):
    print(N+10)

Overwriting test_file.py


In [0]:
%run test_file.py

In [0]:
import numpy as np
np.__version__

'1.14.1'

In [0]:
np?

In [0]:
#python is a dynamically typed language. The variables are explicitly not declared and are more than just the value.

In [0]:
L1 = list(range(10)) # The standard Mutable Multi-element container in python is List
type(L1[0])

int

In [0]:
L2=list(str(c) for c in L1) # or L2=[str(c) for c in L1]
L2 # or print(L2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [0]:
# because of Python's dynmamic typing, you can have heterogeneous lists
L3=[True,1,'str',3.0]
[type(item) for item in L3]

[bool, int, str, float]

In [0]:
import array
L=list(range(10))
#type(L)
#print(L[3])
A=array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
R=range(2,5)
R[2] #r[3] will give error, not 5

4

In [0]:
#creating arrays from python lists
import numpy as np
np.array([1,2,3,4]) #np arrays have same type
np.array([1,2.1,3,4]) #upcast if possible or give error
np.array([1,2,3,4],dtype='float32') #dtype is data type explicitly
np.array([range(i,i+3) for i in [2,3,4]]) #multi demensional array. Range a list with int datatype or an array

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [0]:
# Question: Curl call from python notebook/Shell or simply from terminal/postman. do. (curl databricks call)

In [0]:
np.empty(3)

array([0.75, 0.75, 0.  ])

In [0]:
#numpy builtin functyions for generating arrays
#https://docs.google.com/document/d/1k9LBk_WrUr6N1QmNEICrxm5N6BOx5uQwhCtQheZkNyY/edit

In [0]:
x3 = np.random.randint(10, size=(3, 4, 5)) #10 means randomno between 0-9 , 3 means hieght, 4 = rows, 5 =colms
x3

array([[[2, 6, 3, 1, 4],
        [4, 8, 4, 6, 0],
        [4, 1, 5, 7, 0],
        [7, 1, 6, 1, 2]],

       [[0, 4, 2, 2, 8],
        [0, 1, 5, 7, 6],
        [0, 8, 2, 5, 9],
        [1, 2, 5, 8, 3]],

       [[9, 2, 9, 3, 8],
        [8, 6, 4, 4, 9],
        [7, 5, 1, 8, 6],
        [9, 4, 8, 9, 8]]])

In [0]:
x1 = np.random.randint(10, size=6)
x1[0] = 3.14159  # this will be truncated! but modified
x1

In [0]:
x = np.arange(10) #this is an array
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
x[::-1]  # all elements, reversed syntax is start:stop:step
#start:stop is index not row colm, so x[:] =all array, x[:5] from starting to 5th index, x[5:] from 5th index to end
#similarly x[::-1] is only step. ite extends to 2D , where comma separates row, colm

In [0]:
x2 = np.random.randint(10, size=(3, 4)) #10 means randomno between 0-9 
x2

array([[8, 9, 0, 7],
       [7, 7, 0, 7],
       [8, 8, 6, 7]])

In [0]:
x2[:,:] #all array row, colm
x2[:2,2:]  #rows :2 means stop index is 2 (so first two rows),colms 2: means start index is 2 (colm 3rd and 4th (end))
x2[::-1,::-1] #will reverse
#accessing row colm
print(x2[:,0]) # 0 represents index, here first colm will be printed, : means all 
print(x2[0,:]) # 0 represents index, here first rows will be printed, : means all 
print(x2[0]) #prints first row, same as abpove
#note: sub arrays are views on data, meaning if you modify them the original array would also be changed
# to create sub array as copy of data use.copy() in end
x2_sub_copy = x2[:2, :2].copy()

[8 7 8]
[8 9 0 7]
[8 9 0 7]


In [0]:
#do from concatenation of arrays. before that if you can do newaxis. changing 1d to 2d? 

In [0]:
# presto connection, pandas https://docs.google.com/document/d/1j0OsT3rJAsI7kL0eg_uKf9CbdkQ5023KNOaurrIMvzg/edit
values = np.random.randint(1,10,size=5)
values

array([3, 9, 6, 1, 1])

In [0]:
import numpy as np
np.random.seed(0)

def get_reciprocals(values):
    output=np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1/values[i]
        return output

values = np.random.randint(1,10,size=5) # size is length of array
get_reciprocals(values)

array([1.66666667e-001, 0.00000000e+000, 0.00000000e+000,             nan,
       6.93521275e-310])

In [0]:
#vectorized operations in python. (numpy)
#it can be implemented on entire array, and then acts on each element. eg in above example, instead of looping
#and dividing by 1, just do 1/vector_variable

In [0]:
1/values

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [0]:
#you can also use numpy on 2d array, 3d etc
2*np.arange(9).reshape((3,3))
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [0]:
# ** is used for exponent, // for floor division, the % modulus, abs(x) for absolute or np.absolute(x)

In [0]:
#aggregation functions in numpy has NaN safe counterpart which ignores null (marked as NaN) values
# so instead of using np.sum() use np.nansum()
#sum() is inbuilt python func, np.sum() is numpy veriuson, use np version since its faster


In [0]:
import numpy as np
rng=np.random.RandomState(0) #range, randomstate is a probability distribution for random mumbers
x=rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [0]:
x<3 #performs element wise less than operations (ufuncs in numpy) and returns boolean (masking)

array([[False,  True, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [0]:
np.less(x,3) #same as above. to avoid any python's builtin function

array([[False,  True, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

In [0]:
np.sum(x<3)  #using masking to calculate something eg values <3
np.count_nonzero(x<3)
np.sum((x<3)&(x>1)) #can use &,| (or), ^ (Xor), ~ (not)
#xor is exclusive OR,such that 
# 0 0: 0, 
# 0 1: 1,
# 1 0: 1, 
# 1 1: 0

1

In [0]:
sum(x<3) #do not use this,it is python builtin sum, not np sum

array([1, 1, 0, 0])

In [0]:
np.sum(x<3,axis=0) #on row

array([1, 1, 0, 0])

In [0]:
np.sum(x<3,axis=1) #on colm axis

array([1, 0, 1])

In [0]:
np.all(x<3)
np.any(x<3)
np.any(x==3)
np.any(x!=3)

True

In [0]:
#boolean can be used for masking by using boolean as index of array, returns 1D array 
x[x<3]

array([0, 2])

In [0]:
# and and or perform a single Boolean evaluationon an entire object, 
# while & and | perform multiple Booleanevaluations on the content 
# (the individual bits or bytes) of an object.For Boolean NumPy arrays, 
# the latter is nearly always the desiredoperation.

In [0]:
# solve this rainy example, the last use of masking is good
#https://docs.google.com/document/d/1l4iWHsSMCEszFwDIxO2tfF1lBFh6lmdQqlVaQxl3Dew/edit

#ask ire, how to do gist , or create web page from git?
#do from exploring fancy indexing

In [19]:
!pwd

/content


In [26]:
import numpy as np
import pandas as pd

rainfall = pd.read_csv('drive/My Drive/data/Seattle2014.csv')['PRCP'].values
inches = rainfall / 254 #1/10MM inches
inches.shape

(365,)